# Default values for engageware aplications.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Needed values that should be configured in the repo
app: {}
  #appName: int-middle #must be no more than 15 characters
  #appWorkdir: /var/www/html # app workdir define in dockerfile
  #Port: 80 # port expose in your dockerfile
  #dnsName: prueba.dev.agentbot.net # dnsname of your aplication
  #repo:
  #  name: integration-middleware #Bitbucket repo name
  #  ecr: 831731636870.dkr.ecr.us-east-1.amazonaws.com
  #  tag: feature_CORE-676_513
  #resources:
  #  limits:
  #    cpu: "1000m" #maximum cpu per pod
  #    memory: "1024Mi" #maximum memory per pod
  #  requests:
  #    cpu: "500m" #Minimum cpu per pod
  #    memory: "256Mi" #Minimum memory per pod

#healthCheck of your aplication Probes
healthCheck: {}
  #readinessProbe:
  #  Path: /api/v1/check
  #  Port: http
  #livenessProbe:
  #  Path: /api/v1/check
  #  Port: http

#HorizontalPodAutoscaler
autoscaling: {}
  #enabled: false
  #maxReplicas: 2
  #minReplicas: 1
  #cpuScalePercentage: 70
  #memoryScalePercentage: 70

#Istio-Gateway
istio: {}
#  enabled: false
#  virtualService:
#    pathPrefix: /
#    rewrite:
#      enabled: false # enabled for case rewrite pathPrefix for uri
#      uri: /
#  gateway:
#    httpsRedirect: true # true or false to activating redirect SSL
#    ingressgateway: ingressgateway #ingressgateway internal o external service in case of have 2 lb in the same cluster

#Secret
secret: {}
  #ENV: xxxxxxx
  #PROJECTNAME: xxxxxxxx
  #INTEGRATION_MIDDLEWARE_API_CACHE_PREFIX: xxxxxxx
  #INTEGRATION_MIDDLEWARE_REDIS_SERVER: xxxxxxxx