apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.appName }}
  namespace: {{ .Values.app.repo.name }}
  labels:
    app: {{ .Values.app.appName }}
type: Opaque
data: 
  {{- toYaml .Values.secret | nindent 1 }}