apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.appName }}
  namespace: {{ .Values.app.repo.name }}
  labels:
    app: {{ .Values.app.appName }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: {{ .Values.app.Port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.app.appName }}