{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.appName }}
  namespace: {{ .Values.app.repo.name }}
spec:
  hosts:
    - {{ .Values.app.dnsName }}
  gateways:
    - {{ .Values.app.appName }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.istio.virtualService.pathPrefix }}
        {{- if .Values.istio.virtualService.rewrite.enabled }}
        rewrite:
          uri: {{ .Values.istio.virtualService.rewrite.uri }}
        {{- end }}
      route:
        - destination:
            host: {{ .Values.app.appName }}
{{- end }}

